# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "spud_blog"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Greg Woods"]
  s.date = "2012-01-25"
  s.email = "greg@westlakedesign.com"
  s.files = [
    "app/assets/javascripts/spud/admin/users.js",
    "app/assets/javascripts/spud/user_sessions.js",
    "app/helpers/spud/admin/users_helper.rb",
    "app/helpers/spud/user_sessions_helper.rb",
    "config/application.rb",
    "config/boot.rb",
    "config/routes.rb",
    "lib/spud_admin.rb",
    "lib/spud_admin/engine.rb"
  ]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Spud Blog Engine"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<spud_admin>, [">= 0"])
      s.add_runtime_dependency(%q<will_paginate>, [">= 0"])
    else
      s.add_dependency(%q<spud_admin>, [">= 0"])
      s.add_dependency(%q<will_paginate>, [">= 0"])
    end
  else
    s.add_dependency(%q<spud_admin>, [">= 0"])
    s.add_dependency(%q<will_paginate>, [">= 0"])
  end
end

